# Generated by Django 2.0.3 on 2018-10-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20181023_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mask',
            old_name='map_id',
            new_name='map',
        ),
    ]
